export function puzzleCreation() {
    const puzzles = [
        {
            background: "Opera.webp",
            category: "Ephitet",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "",
            piece15: "L",
            piece16: "A",
            piece17: "D",
            piece18: "Y",
            piece19: "",
            piece20: "O",
            piece21: "F",
            piece22: "",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "T",
            piece28: "H",
            piece29: "E",
            piece30: "",
            piece31: "L",
            piece32: "A",
            piece33: "K",
            piece34: "E",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "",
            piece40: "",
            piece41: "",
            piece42: "",
            piece43: "",
            piece44: "",
            piece45: "",
            piece46: "",
            piece47: "",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        }, 

        {
            background: "awakening.png",
            category: "Quote",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "P",
            piece15: "I",
            piece16: "C",
            piece17: "K",
            piece18: "",
            piece19: "A",
            piece20: "",
            piece21: "G",
            piece22: "O",
            piece23: "D",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "A",
            piece28: "N",
            piece29: "D",
            piece30: "",
            piece31: "P",
            piece32: "R",
            piece33: "A",
            piece34: "Y",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "",
            piece40: "",
            piece41: "",
            piece42: "",
            piece43: "",
            piece44: "",
            piece45: "",
            piece46: "",
            piece47: "",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "tellius.png",
            category: "Weapons",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "",
            piece15: "R",
            piece16: "A",
            piece17: "G",
            piece18: "N",
            piece19: "E",
            piece20: "L",
            piece21: "L",
            piece22: "",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "",
            piece28: "",
            piece29: "A",
            piece30: "N",
            piece31: "D",
            piece32: "",
            piece33: "",
            piece34: "",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "A",
            piece40: "L",
            piece41: "O",
            piece42: "N",
            piece43: "D",
            piece44: "I",
            piece45: "T",
            piece46: "E",
            piece47: "",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "valentia.png",
            category: "Meme",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "S",
            piece15: "O",
            piece16: "M",
            piece17: "M",
            piece18: "I",
            piece19: "E",
            piece20: "'",
            piece21: "S",
            piece22: "",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "L",
            piece27: "A",
            piece28: "R",
            piece29: "G",
            piece30: "E",
            piece31: "",
            piece32: "",
            piece33: "",
            piece34: "",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "U",
            piece39: "N",
            piece40: "N",
            piece41: "A",
            piece42: "T",
            piece43: "U",
            piece44: "R",
            piece45: "A",
            piece46: "L",
            piece47: "S",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "crimea.png",
            category: "Quote",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "",
            piece15: "D",
            piece16: "E",
            piece17: "C",
            piece18: "E",
            piece19: "I",
            piece20: "T",
            piece21: "F",
            piece22: "U",
            piece23: "L",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "L",
            piece28: "Y",
            piece29: "I",
            piece30: "N",
            piece31: "G",
            piece32: "",
            piece33: "",
            piece34: "",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "S",
            piece40: "Q",
            piece41: "U",
            piece42: "I",
            piece43: "N",
            piece44: "T",
            piece45: "Y",
            piece46: "",
            piece47: "",
            piece48: "",
            piece49: "",
            piece50: "C",
            piece51: "O",
            piece52: "W",
            piece53: "A",
            piece54: "R",
            piece55: "D",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "holy-tomb.png",
            category: "Title",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "",
            piece15: "T",
            piece16: "H",
            piece17: "E",
            piece18: "",
            piece19: "",
            piece20: "",
            piece21: "",
            piece22: "",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "D",
            piece28: "I",
            piece29: "V",
            piece30: "I",
            piece31: "N",
            piece32: "E",
            piece33: "",
            piece34: "",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "S",
            piece40: "O",
            piece41: "V",
            piece42: "E",
            piece43: "R",
            piece44: "E",
            piece45: "I",
            piece46: "G",
            piece47: "N",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "ss.png",
            category: "Before & After Title",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "",
            piece15: "",
            piece16: "A",
            piece17: "S",
            piece18: "H",
            piece19: "E",
            piece20: "N",
            piece21: "",
            piece22: "",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "",
            piece27: "",
            piece28: "D",
            piece29: "E",
            piece30: "M",
            piece31: "O",
            piece32: "N",
            piece33: "",
            piece34: "",
            piece35: "",
            piece36: "",
            piece37: "",
            piece38: "",
            piece39: "",
            piece40: "K",
            piece41: "I",
            piece42: "N",
            piece43: "G",
            piece44: "",
            piece45: "",
            piece46: "",
            piece47: "",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        },

        {
            background: "Opera.webp",
            category: "Meme",
            piece1: "",
            piece2: "",
            piece3: "",
            piece4: "",
            piece5: "",
            piece6: "",
            piece7: "",
            piece8: "",
            piece9: "",
            piece10: "",
            piece11: "",
            piece12: "",
            piece13: "",
            piece14: "G",
            piece15: "R",
            piece16: "O",
            piece17: "A",
            piece18: "N",
            piece19: "S",
            piece20: "",
            piece21: "O",
            piece22: "F",
            piece23: "",
            piece24: "",
            piece25: "",
            piece26: "I",
            piece27: "N",
            piece28: "C",
            piece29: "R",
            piece30: "E",
            piece31: "A",
            piece32: "S",
            piece33: "I",
            piece34: "N",
            piece35: "G",
            piece36: "",
            piece37: "",
            piece38: "D",
            piece39: "I",
            piece40: "S",
            piece41: "C",
            piece42: "O",
            piece43: "M",
            piece44: "F",
            piece45: "O",
            piece46: "R",
            piece47: "T",
            piece48: "",
            piece49: "",
            piece50: "",
            piece51: "",
            piece52: "",
            piece53: "",
            piece54: "",
            piece55: "",
            piece56: "",
            piece57: "",
            piece58: "",
        }
    ]

    // const puzzleBase = [
    //     {
    //         category: "",
    //         piece1: "",
    //         piece2: "",
    //         piece3: "",
    //         piece4: "",
    //         piece5: "",
    //         piece6: "",
    //         piece7: "",
    //         piece8: "",
    //         piece9: "",
    //         piece10: "",
    //         piece11: "",
    //         piece12: "",
    //         piece13: "",
    //         piece14: "",
    //         piece15: "",
    //         piece16: "",
    //         piece17: "",
    //         piece18: "",
    //         piece19: "",
    //         piece20: "",
    //         piece21: "",
    //         piece22: "",
    //         piece23: "",
    //         piece24: "",
    //         piece25: "",
    //         piece26: "",
    //         piece27: "",
    //         piece28: "",
    //         piece29: "",
    //         piece30: "",
    //         piece31: "",
    //         piece32: "",
    //         piece33: "",
    //         piece34: "",
    //         piece35: "",
    //         piece36: "",
    //         piece37: "",
    //         piece38: "",
    //         piece39: "",
    //         piece40: "",
    //         piece41: "",
    //         piece42: "",
    //         piece43: "",
    //         piece44: "",
    //         piece45: "",
    //         piece46: "",
    //         piece47: "",
    //         piece48: "",
    //         piece49: "",
    //         piece50: "",
    //         piece51: "",
    //         piece52: "",
    //         piece53: "",
    //         piece54: "",
    //         piece55: "",
    //         piece56: "",
    //         piece57: "",
    //         piece58: "",
    //     }
    // ]

    return puzzles;
}